import { Banco } from './banco';

export const BANCOS: Banco[] = [
    {nombre: 'Banco Caroní'},
    {nombre: 'Banco Canarias de Venezuela'},
    {nombre: 'Banco Confederado'},
    {nombre: 'Bolívar Banco'},
    {nombre: 'Corp Banca'},
    {nombre: 'Banco de Crédito de Colombia'},
    {nombre: 'Banco Do Brasil'},
    {nombre: 'Banco del Caribe'},
    {nombre: 'Bancoro'},
    {nombre: 'Banco de Venezuela'},
    {nombre: 'Banco Sofitasa'},
    {nombre: 'Banpro'},
    {nombre: 'Stanford Bank'},
    {nombre: 'Banco Provincial'},
    {nombre: 'Banco Tequendama'},
    {nombre: 'Banesco'},
    {nombre: 'Banco Fondo Común'},
    {nombre: 'Banfoandes'},
    {nombre: 'Banco Occidental de Descuento'},
    {nombre: 'Banco Venezolano de Crédito'},
    {nombre: 'Central'},
    {nombre: 'Banco Guayana'},
    {nombre: 'Banco Exterior'},
    {nombre: 'Banco Industrial de Venezuela'},
    {nombre: 'Banco Mercantil'},
    {nombre: 'Banco Plaza'},
    {nombre: 'Citibank'},
    {nombre: 'Total Bank'},
    {nombre: 'Instituto Municipal de Crédito Popular'},
    {nombre: 'Nuevo Mundo'},
    {nombre: 'Banco Federal'},
    {nombre: 'Casa Propia'},
    {nombre: 'Del Sur'},
    {nombre: 'Mi Casa'},
    {nombre: 'Merenap'},
];